version: '3'
services:
  local_development_server:
    build: .
    restart: "no"
    ports:
      - "5000:5000"
    environment:
      LOG_LEVEL: info
    volumes:
      - './:/usr/src/'
    entrypoint: [ "mkdocs", "serve", "-v", "--dev-addr=0.0.0.0:5000" ]